### PR TITLE
First batch of includes

### PR DESCRIPTION
**Pull request by yammes08**
- Created four include templates based on a selection of guide profiles
- Removed user-choice scoring sections from includes
- Added these to the includes.json

### CODE REVIEW

**Comment by yammes08** [comment]
@rcdailey - tagging for a general review, but also the YAML Lint checks are failing...have I got something wrong with these, or is it because the rules are expecting a different indentation?

**Comment by rcdailey** [comment]
Hey yammes, the issue is that everything is indented by 2 spaces from the very left column. You only need to shift everything back 2 spaces and it'll clear up the lint issues.

**Comment by rcdailey** [comment]
As an example, your current file indentation looks like this:
```yml
  quality_definition:
    type: movie
```
But it needs to shift left by 2 spaces:
```yml
quality_definition:
  type: movie
```
I'm only showing a very small piece for example purposes, but this would apply to the entire file.

**Comment by yammes08** [comment]
> As an example, your current file indentation looks like this:
> 
> ```yaml
>   quality_definition:
>     type: movie
> ```
> 
> But it needs to shift left by 2 spaces:
> 
> ```yaml
> quality_definition:
>   type: movie
> ```
> 
> I'm only showing a very small piece for example purposes, but this would apply to the entire file.

I was *certain* I'd done that already which is why I asked...but not, I'd not done enough...sorry 😄

**Comment by yammes08** [comment]
Fixed now - does everything else look alright?

**Comment by rcdailey** [comment]
Seems ok so far! I think where things will be more interesting is when you start including them in templates. We talked a little about this a few days ago, but you could either commit template changes to your fork (and change the config repo URL in your `settings.yml`) or just create copies in this repo for now so they don't interfere with the stable release.

You could go a number of ways. Did you have a plan already? Or were you just going to manipulate local configs for now to see how they would work if you had created them with `config create`?

**Review by rcdailey — APPROVED** [review]

**Comment by yammes08** [comment]
> Seems ok so far! I think where things will be more interesting is when you start including them in templates. We talked a little about this a few days ago, but you could either commit template changes to your fork (and change the config repo URL in your `settings.yml`) or just create copies in this repo for now so they don't interfere with the stable release.
> 
> You could go a number of ways. Did you have a plan already? Or were you just going to manipulate local configs for now to see how they would work if you had created them with `config create`?

For now, the idea is that I'll locally build 'new-style' templates that reference these includes, and then should they pass testing without issue then I'd look to update the templates themselves in the repo to match what I've built locally.

I've deviated a little from our last discussion on this, and haven't split quality profiles and custom formats into separate sections. For includes that are designed to mirror the guides, I don't think it's necessary.

**Comment by rcdailey** [comment]
Sounds like a great plan yammes. Good work! I think you'll eventually get a feel for how granular you want your include files as you play around with these more.

**Comment by rcdailey** [comment]
@yammes08 I went ahead and merged this so we have something to test with.

**Comment by yammes08** [comment]
> @yammes08 I went ahead and merged this so we have something to test with.

No problem, thanks for this, I just didn't get to it.

**Pull request merged**
