### PR TITLE
Add DSCP and SYFY to sonarr cf

### PR DESCRIPTION
**Pull request by onedr0p**

### CODE REVIEW

**Comment by yammes08** [comment]
DSCP isn't in the General Streaming Services group on the equivalent guides pages - which is probably an error, but it will need to be addressed there before it can be merged here. I will take that forward.

**Comment by rcdailey** [comment]
@yammes08 Could you provide a brief status update when you get a chance? If you need more time, please let me know. I just want to make sure this PR doesn't need to be closed.

**Comment by yammes08** [comment]
> @yammes08 Could you provide a brief status update when you get a chance? If you need more time, please let me know. I just want to make sure this PR doesn't need to be closed.

Status update: I'm useless 😄 - going to do a full review of the whole repo later this evening to fix up any updates and/or omissions.

**Comment by yammes08** [comment]
I haven't had a response back to this on the Guides side of things yet. That said, I think it's likely that DSCP should be in the General section, so I'm happy to approve this here and fix things up in reverse.

**Pull request merged**
