### PR TITLE
fix(french-radarr): update recyclarr configs

### PR DESCRIPTION
**Pull request by NiceTSY**
## Purpose

Update all 8 French Radarr Recyclarr template configuration files to latest development.

## To-do list

- [x] French HD Bluray + WEB (MULTi)
- [x] French HD Bluray + WEB (VOSTFR)
- [x] French HD Remux + WEB (MULTi)
- [x] French HD Remux + WEB (VOSTFR)
- [x] French Remux + WEB 2160p (MULTi)
- [x] French Remux + WEB 2160p (VOSTFR)
- [x] French UHD Bluray + WEB (MULTi)
- [x] French UHD Bluray + WEB (VOSTFR)

### CODE REVIEW

**Comment by rcdailey** [comment]
Never mind, I was able to rebase from the PR 👍🏻 

I will let yammes approve and merge.

**Comment by NiceTSY** [comment]
Just saw that the latest merge from 'master' added some yamlint errors, will correct them tomorrow :)

**Comment by rcdailey** [comment]
> Just saw that the latest merge from 'master' added some yamlint errors, will correct them tomorrow :)

Yes, I recently "polished up" the yaml lint rules. I apologize for the inconvenience!

**Comment by NiceTSY** [comment]
Haha, no worries, I should have seen them as well before the PR

**Comment by yammes08** [comment]
@NiceTSY - I've noticed you've changed the name of the instances in the config files. These will still work fine as they are, but if any of your users are copy/pasting updated copies of the files they'll get errors about custom format ownership unless they use `replace_existing_custom_formats`. Just wanted to check with you before merging.

**Comment by rcdailey** [comment]
@yammes08 I just want to clarify that as of modern versions of Recyclarr, the instance name is no longer a part of the hash that gets generated for the cache directory. So the name changes at face value shouldn't cause issues there; although we still need to be careful of conflicting names (i.e. two or more files with the same instance names).

**Comment by yammes08** [comment]
Aaah yes - forgot that! These are good to go then.

**Pull request merged**
