### PR TITLE
update `quality_profiles` to `assign_scores_to` for `sqp-1-1080p.yml` template

### PR DESCRIPTION
**Pull request by OwenVey**

### CODE REVIEW

**Comment by rcdailey** [comment]
Could you go ahead and update all of the templates with this change?

**Comment by OwenVey** [comment]
Other templates already were updated. Looks like it was just missed in https://github.com/recyclarr/config-templates/pull/86

**Comment by rcdailey** [comment]
My mistake, I forgot that the others had been addressed. Thank you for the reminder and also for the fix!

**Comment by rcdailey** [comment]
Once you address the workflow failures I'll get this merged for you.

**Review by yammes08 — APPROVED** [review]

**Comment by yammes08** [comment]
Thank you @OwenVey for changing the date...twice! Appreciate the fix 🙂

**Pull request merged**
