### PR TITLE
feat: added top level templates for the German Guide

### PR DESCRIPTION
**Pull request by Lokilicious**
Added the 3 top level templates for the German Guide

### CODE REVIEW

**Comment by rcdailey** [comment]
@yammes08 This PR looks good to me, but you're more in-tune with the guides than I am. If you sign off on this I'm happy to merge it.

**Comment by yammes08** [comment]
@Lokilicious - these need to be added to templates.json

**Review by yammes08 — CHANGES_REQUESTED** [review]
Please add these to templates.json

**Comment by rcdailey** [comment]
> Please add these to templates.json

Oh that's a really good catch. I apparently didn't look hard enough.

**Comment by Lokilicious** [comment]
@yammes08 done 👍

**Review by yammes08 — APPROVED** [review]

**Pull request merged**
